openapi: 3.1.0
info:
  title: XRP Pattern Scanner Actions
  version: "0.1.0"
  description: 取得 XRP/USDT 即時價格、K 線、技術指標與圖像，並可寫入/讀取分析經驗。
servers:
  - url: https://xrp-actions.onrender.com

paths:
  /:
    get:
      summary: Root
      operationId: root
      responses:
        "200":
          description: OK

  /price:
    get:
      summary: Current price
      operationId: getPrice
      parameters:
        - in: query
          name: symbol
          required: true
          schema: { type: string }
          example: XRP/USDT
        - in: query
          name: precision
          description: 小數位數（四捨五入）
          required: false
          schema: { type: integer, minimum: 0, maximum: 10, default: 4 }
          example: 4
        - in: query
          name: source
          description: 價源（ticker=撮合成交價；book=訂單簿近似）
          required: false
          schema:
            type: string
            enum: [ticker, book]
            default: book
          example: book
      responses:
        "200":
          description: Current price
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PriceResponse"

  /klines:
    get:
      summary: Klines
      operationId: getKlines
      parameters:
        - in: query
          name: symbol
          required: true
          schema: { type: string }
          example: XRP/USDT
        - in: query
          name: interval
          required: true
          schema:
            type: string
            enum: [5m, 15m, 30m, 1h, 4h, 1d]
          example: 15m
        - in: query
          name: limit
          required: false
          schema: { type: integer, minimum: 50, maximum: 500, default: 200 }
          example: 200
      responses:
        "200":
          description: OHLCV rows
          content:
            application/json:
              schema:
                type: object
                properties:
                  exchange: { type: string, example: binance }
                  symbol: { type: string, example: XRP/USDT }
                  interval: { type: string, example: 15m }
                  rows:
                    type: array
                    items:
                      $ref: "#/components/schemas/OHLCV"

  /indicators:
    get:
      summary: Indicators (BB/KDJ/MACD)
      operationId: getIndicators
      parameters:
        - in: query
          name: symbol
          required: true
          schema: { type: string }
          example: XRP/USDT
        - in: query
          name: interval
          required: true
          schema:
            type: string
            enum: [5m, 15m, 30m, 1h, 4h, 1d]
          example: 15m
        - in: query
          name: limit
          required: false
          schema: { type: integer, minimum: 50, maximum: 200, default: 200 }
          example: 200
      responses:
        "200":
          description: Indicators snapshot
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IndicatorsResponse"

  /chart:
    get:
      summary: Candlestick chart (PNG)
      operationId: getChart
      parameters:
        - in: query
          name: symbol
          required: true
          schema: { type: string }
          example: XRP/USDT
        - in: query
          name: interval
          required: true
          schema:
            type: string
            enum: [5m, 15m, 30m, 1h, 4h, 1d]
          example: 15m
        - in: query
          name: limit
          required: false
          schema: { type: integer, minimum: 100, maximum: 500, default: 300 }
          example: 300
        - in: query
          name: sma
          description: 簡單移動平均（單一週期）
          required: false
          schema: { type: integer, minimum: 2, maximum: 200, default: 20 }
          example: 20
        - in: query
          name: bbands
          description: 布林帶週期（K=2 固定）
          required: false
          schema: { type: integer, minimum: 5, maximum: 100, default: 20 }
          example: 20
        - in: query
          name: show_kdj
          required: false
          schema: { type: boolean, default: true }
          example: true
        - in: query
          name: show_macd
          required: false
          schema: { type: boolean, default: true }
          example: true
        - in: query
          name: volume
          description: 是否顯示成交量
          required: false
          schema: { type: boolean, default: true }
          example: true
      responses:
        "200":
          description: PNG image
          content:
            image/png:
              schema:
                type: string
                format: binary

  /experience/log:
    post:
      summary: Write one analysis experience
      operationId: postExperienceLog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExperienceLogIn"
      responses:
        "200":
          description: Saved
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok: { type: boolean, example: true }
                  id: { type: string, example: "e3f5c1a…" }

  /experience/recent:
    get:
      summary: Read recent experiences
      operationId: getExperienceRecent
      parameters:
        - in: query
          name: n
          description: 取回筆數
          required: false
          schema: { type: integer, minimum: 1, maximum: 100, default: 20 }
          example: 10
      responses:
        "200":
          description: Recent items
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExperienceRecent"

components:
  schemas:
    PriceResponse:
      type: object
      properties:
        exchange: { type: string, example: binance }
        symbol: { type: string, example: XRP/USDT }
        price: { type: number, example: 2.9725 }
        ts: { type: integer, example: 1757362813878 }
        time_local: { type: string, example: "下午 03 點 21 分" }

    OHLCV:
      type: object
      properties:
        ts:   { type: integer, example: 1757328000000 }
        open:  { type: number, example: 2.8824 }
        high:  { type: number, example: 2.9790 }
        low:   { type: number, example: 2.8750 }
        close: { type: number, example: 2.9734 }
        volume:{ type: number, example: 213440.5 }

    IndicatorsResponse:
      type: object
      properties:
        exchange: { type: string, example: binance }
        symbol: { type: string, example: XRP/USDT }
        interval: { type: string, example: 15m }
        last:
          type: object
          properties:
            open:  { type: number, example: 2.9700 }
            high:  { type: number, example: 2.9790 }
            low:   { type: number, example: 2.9730 }
            close: { type: number, example: 2.9734 }
            volume:{ type: number, example: 213440.5 }
        bbands:
          type: object
          properties:
            upper: { type: number, example: 2.9862 }
            middle:{ type: number, example: 2.9670 }
            lower: { type: number, example: 2.9480 }
            k:     { type: number, example: 2 }
            n:     { type: integer, example: 20 }
        kdj:
          type: object
          properties:
            k: { type: number, example: 49.85 }
            d: { type: number, example: 55.285 }
            j: { type: number, example: 39.077 }
        macd:
          type: object
          properties:
            dif:   { type: number, example: 0.0041 }
            dea:   { type: number, example: 0.0057 }
            hist:  { type: number, example: -0.0016 }
            fast:  { type: integer, example: 12 }
            slow:  { type: integer, example: 26 }
            signal:{ type: integer, example: 9 }

    ExperienceLogIn:
      type: object
      required: [symbol, interval, pattern, outcome]
      properties:
        symbol:   { type: string, example: XRP/USDT }
        interval: { type: string, example: 15m }
        pattern:  { type: string, example: three_white_soldiers }
        outcome:  { type: string, example: bullish }
        notes:    { type: string, example: "依《蠟燭圖精解》章節要點，突破伴隨量能放大。" }

    ExperienceItem:
      type: object
      properties:
        id: { type: string, example: "e3f5c1a…" }
        ts: { type: integer, example: 1757362813878 }
        time_local: { type: string, example: "下午 03 點 21 分" }
        symbol: { type: string, example: XRP/USDT }
        interval: { type: string, example: 15m }
        pattern: { type: string, example: three_white_soldiers }
        outcome: { type: string, example: bullish }
        notes: { type: string, example: "回測支撐有效；量能維持。" }

    ExperienceRecent:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/ExperienceItem"
